minVersion: '2.21.1'
changelog:
  policy: auto
versioning:
  policy: auto
preReleaseCommand: node --experimental-strip-types script/bump-version.ts --pre
postReleaseCommand: node --experimental-strip-types script/bump-version.ts --post
artifactProvider:
  name: github
  config:
    artifacts:
      ci.yml:
        - 'sentry-*'
        - 'npm-package'
        - 'gh-pages'
targets:
  - name: npm
  - name: github
  - name: gh-pages
