minVersion: '2.19.0'
changelog:
  policy: auto
versioning:
  policy: auto
preReleaseCommand: node --experimental-strip-types script/bump-version.ts --pre
postReleaseCommand: node --experimental-strip-types script/bump-version.ts --post
requireNames:
  - /^sentry-.+$/
  - /^sentry-.*\.tgz$/
targets:
  - name: npm
  - name: github
  - name: gh-pages
