/**
 * Unit Tests for TRDIFF10 Binary Patch Application
 *
 * Note: Core invariants (offtin sign/magnitude, parsePatchHeader non-negative
 * values) are tested via property-based tests in bspatch.property.test.ts.
 * These tests focus on fixture-based patch application, negative-value rejection
 * (property generator clears sign bits), and error messages.
 *
 * Tests the bspatch implementation against real TRDIFF10 patches
 * generated by zig-bsdiff v0.1.19 (stored as test fixtures).
 */

import { describe, expect, test } from "bun:test";
import { unlinkSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { applyPatch, parsePatchHeader } from "../../src/lib/bspatch.js";

const FIXTURES_DIR = join(import.meta.dir, "../fixtures/patches");

describe("parsePatchHeader: fixtures", () => {
  test("parses valid small fixture header", async () => {
    const patchData = new Uint8Array(
      await Bun.file(join(FIXTURES_DIR, "small.trdiff10")).arrayBuffer()
    );
    const header = parsePatchHeader(patchData);
    expect(header.controlLen).toBeGreaterThan(0);
    expect(header.diffLen).toBeGreaterThan(0);
    expect(header.newSize).toBe(54); // "Hello, World! This is the new file content. Version 2."
  });

  test("parses valid large fixture header", async () => {
    const patchData = new Uint8Array(
      await Bun.file(join(FIXTURES_DIR, "large.trdiff10")).arrayBuffer()
    );
    const header = parsePatchHeader(patchData);
    expect(header.controlLen).toBeGreaterThan(0);
    expect(header.diffLen).toBeGreaterThanOrEqual(0);
    expect(header.newSize).toBe(65_536);
  });

  test("rejects truncated patch (header claims more data than exists)", () => {
    const truncated = new Uint8Array(32);
    truncated.set(new TextEncoder().encode("TRDIFF10"));
    truncated[8] = 100; // controlLen = 100
    expect(() => parsePatchHeader(truncated)).toThrow("exceed file size");
  });

  test("rejects negative header values", () => {
    // Property generator clears sign bits (patched[15] %= 128) so never
    // exercises the negative-length error path — this test fills that gap
    const buf = new Uint8Array(64);
    buf.set(new TextEncoder().encode("TRDIFF10"));
    // offtin reads sign from bit 7 of byte 7 within each 8-byte field.
    // controlLen is at offset 8, so sign bit is byte 15.
    // Need non-zero magnitude + sign bit for a negative result.
    buf[8] = 1; // non-zero low byte → magnitude > 0
    buf[15] = 0x80; // Set sign bit → negative controlLen
    expect(() => parsePatchHeader(buf)).toThrow("negative");
  });
});

describe("applyPatch", () => {
  function tempFile(name: string): string {
    return join(tmpdir(), `bspatch-test-${Date.now()}-${name}`);
  }

  test("patches small text files correctly", async () => {
    const oldPath = join(FIXTURES_DIR, "small-old.bin");
    const patchData = new Uint8Array(
      await Bun.file(join(FIXTURES_DIR, "small.trdiff10")).arrayBuffer()
    );
    const destPath = tempFile("small-out.bin");

    try {
      const sha256 = await applyPatch(oldPath, patchData, destPath);

      const expected = await Bun.file(
        join(FIXTURES_DIR, "small-new.bin")
      ).arrayBuffer();
      const actual = await Bun.file(destPath).arrayBuffer();
      expect(new Uint8Array(actual)).toEqual(new Uint8Array(expected));

      const expectedHash = new Bun.CryptoHasher("sha256")
        .update(new Uint8Array(expected))
        .digest("hex");
      expect(sha256).toBe(expectedHash);
    } finally {
      try {
        unlinkSync(destPath);
      } catch {
        // Ignore cleanup errors
      }
    }
  });

  test("patches large binary files correctly", async () => {
    const oldPath = join(FIXTURES_DIR, "large-old.bin");
    const patchData = new Uint8Array(
      await Bun.file(join(FIXTURES_DIR, "large.trdiff10")).arrayBuffer()
    );
    const destPath = tempFile("large-out.bin");

    try {
      const sha256 = await applyPatch(oldPath, patchData, destPath);

      const expected = await Bun.file(
        join(FIXTURES_DIR, "large-new.bin")
      ).arrayBuffer();
      const actual = await Bun.file(destPath).arrayBuffer();
      expect(new Uint8Array(actual)).toEqual(new Uint8Array(expected));

      const expectedHash = new Bun.CryptoHasher("sha256")
        .update(new Uint8Array(expected))
        .digest("hex");
      expect(sha256).toBe(expectedHash);
    } finally {
      try {
        unlinkSync(destPath);
      } catch {
        // Ignore cleanup errors
      }
    }
  });

  test("returns correct SHA-256 hex digest", async () => {
    const oldPath = join(FIXTURES_DIR, "small-old.bin");
    const patchData = new Uint8Array(
      await Bun.file(join(FIXTURES_DIR, "small.trdiff10")).arrayBuffer()
    );
    const destPath = tempFile("sha256-out.bin");

    try {
      const sha256 = await applyPatch(oldPath, patchData, destPath);
      expect(sha256).toMatch(/^[0-9a-f]{64}$/);
      expect(sha256.length).toBe(64);
    } finally {
      try {
        unlinkSync(destPath);
      } catch {
        // Ignore cleanup errors
      }
    }
  });

  test("rejects non-TRDIFF10 magic", async () => {
    const oldPath = join(FIXTURES_DIR, "small-old.bin");
    const buf = new Uint8Array(64);
    buf.set(new TextEncoder().encode("BSDIFF40"));
    const destPath = tempFile("badmagic-out.bin");

    try {
      await expect(applyPatch(oldPath, buf, destPath)).rejects.toThrow(
        "Invalid patch format"
      );
    } finally {
      try {
        unlinkSync(destPath);
      } catch {
        // Ignore cleanup errors
      }
    }
  });
});
