/**
 * Write the checklist covering the half of the migration a codemod cannot do.
 *
 * This file is the handoff to an agent, so it is written for one: numbered
 * working instructions, a `file:line` per entry, and a closing verification
 * checklist. It carries only what the tasks actually found in *this* repo,
 * because a report listing every breaking change is the migration guide, and
 * the guide already exists and is better. The header says so and links it.
 *
 * There is no relevance filter and no catalog. An entry appears because a task
 * found something, and a task that found nothing writes nothing.
 *
 * Findings are deliberately broad. A check task matches text, not meaning, so
 * some listed files will need no change. The report says so and tells the
 * reader to skip them. For a change that cannot be automated, a false positive
 * costs a minute and a miss costs a silent breaking change.
 */

import {
  defineMigrationTask,
  type TaskWithOptions,
} from "../../../framework.js";
import type { Finding } from "../../../types.js";
import { guide } from "../guide.js";
import { TODO_MARKER } from "../marker.js";

export const CHECKLIST_FILE = "SENTRY-JAVASCRIPT-V11-MIGRATION.md";

/**
 * Marks the file as ours.
 *
 * Without it, a re-run would silently overwrite a file the user wrote by hand
 * at the same path. That is the difference between a tool that is safe to run
 * again and one that eats work.
 */
export const GENERATED_MARKER = "<!-- Generated by `sentry migrate` -->";

type Entry = {
  title: string;
  /** What the reader has to decide, from the task that found it. */
  guidance: string | null;
  hits: Finding[];
  docs: string;
};

/**
 * One entry per task that reported manual work, in the order the tasks ran.
 *
 * Grouping by task rather than by topic is what removes the bookkeeping: the
 * heading, the guidance and the link all come from the task that produced the
 * findings, so an entry cannot describe something no task looked for, and a
 * task cannot report findings under someone else's heading.
 */
function buildEntries(findings: Finding[], tasks: TaskWithOptions[]): Entry[] {
  const byTask = new Map<string, Finding[]>();
  for (const finding of findings) {
    if (finding.kind !== "manual") {
      continue;
    }
    byTask.set(finding.taskId, [
      ...(byTask.get(finding.taskId) ?? []),
      finding,
    ]);
  }

  return tasks.flatMap((task) => {
    const hits = byTask.get(task.id);
    return hits
      ? [
          {
            title: task.description,
            guidance: task.guidance ?? null,
            hits,
            docs: task.docs ?? guide(),
          },
        ]
      : [];
  });
}

function renderEntry(entry: Entry): string {
  const lines = [`### ${entry.title}`, ""];

  if (entry.guidance) {
    lines.push(entry.guidance, "");
  }

  lines.push("#### Found here", "");
  for (const hit of entry.hits) {
    lines.push(`- [ ] \`${hit.file}:${hit.line}\` — ${hit.message}`);
  }

  lines.push(
    "",
    "#### Reference",
    "",
    `- [Migrating to v11](${entry.docs})`,
    ""
  );
  return lines.join("\n");
}

export function renderReport(entries: Entry[], fixedCount: number): string {
  return `${GENERATED_MARKER}
# Sentry JavaScript SDK: v10 → v11 migration tasks

\`sentry migrate\` applied ${fixedCount} change${fixedCount === 1 ? "" : "s"} automatically.
What follows is what it could not: changes that depend on what your code means,
or that live outside this repository.

This lists what \`sentry migrate\` found in this project, not every change in
the release. The [full migration guide](${guide()}) is the complete list. Skim
it once you have worked through this file.

Findings are intentionally broad and may include files that need no change.

An AI agent can work through these one at a time:

1. Read the linked documentation before changing code.
2. Inspect every listed file and its surrounding context.
3. Skip a finding when the file turns out not to be affected.
4. Make the smallest necessary change. Do not refactor anything unrelated.
5. Ask the user when the intent of the code cannot be inferred.
6. Run the project's typecheck, tests and build afterwards.

Also search the project for \`${TODO_MARKER}\` comments. They mark
follow-up work at the exact line it applies to.

## Migration tasks

${entries.map(renderEntry).join("\n")}
## Final verification

- [ ] Work through every task above, skipping findings that do not apply.
- [ ] Resolve every remaining \`${TODO_MARKER}\` comment.
- [ ] Install dependencies. \`sentry migrate\` edits \`package.json\` but never installs.
- [ ] Run the project's typecheck and tests.
- [ ] Build the project successfully.
- [ ] Delete this file once the migration is complete.

\`sentry migrate\` is safe to run again.
`;
}

/**
 * Reporting is a task like any other so that `--only` and `--skip` can turn it
 * off. It runs last and does nothing itself: the report needs the complete
 * finding set, which only exists once every task has run, so the runner calls
 * `buildReport` after this returns.
 */
export const writeMigrationReport = defineMigrationTask({
  id: "report",
  description: `Write ${CHECKLIST_FILE} describing the work left to do`,
  run: () => {
    // Intentionally empty. See the docstring.
  },
});

/** Build the report. Called by the runner after all tasks have completed. */
export function buildReport(
  findings: Finding[],
  tasks: TaskWithOptions[]
): string | null {
  const entries = buildEntries(findings, tasks);
  if (entries.length === 0) {
    return null;
  }
  const fixedCount = findings.filter(
    (finding) => finding.kind === "fixed"
  ).length;
  return renderReport(entries, fixedCount);
}
