// Auto-generated by script/generate-sdk.ts — DO NOT EDIT
// Run `bun run generate:sdk` to regenerate.

import type { buildInvoker } from "./lib/sdk-invoke.js";
import type {
  SentryEvent,
  SentryIssue,
  SentryOrganization,
  SentryProject,
  SentryTeam,
  SpanListItem,
  TraceSpan,
  TransactionListItem,
} from "./types/index.js";

// --- Parameter types ---

export type OrganizationsListParams = {
  /** Maximum number of organizations to list */
  limit?: number;
};

export type OrganizationsGetParams = {
  /** Org identifier */
  org?: string;
};

export type ProjectsListParams = {
  /** Target identifier */
  target?: string;
  /** Maximum number of projects to list */
  limit?: number;
  /** Filter by platform (e.g., javascript, python) */
  platform?: string;
  /** Pagination cursor (use "last" to continue from previous page) */
  cursor?: string;
};

export type ProjectsGetParams = {
  /** Target identifier */
  target?: string;
};

export type IssuesListParams = {
  /** Org slug */
  org: string;
  /** Project slug */
  project: string;
  /** Search query (Sentry search syntax) */
  query?: string;
  /** Maximum number of issues to list */
  limit?: number;
  /** Sort by: date, new, freq, user */
  sort?: string;
  /** Time period for issue activity (e.g. 24h, 14d, 90d) */
  period?: string;
  /** Pagination cursor for <org>/ or multi-target modes (use "last" to continue) */
  cursor?: string;
};

export type IssuesGetParams = {
  /** IssueId identifier */
  issueId: string;
  /** Span tree depth limit (number, "all" for unlimited, "no" to disable) */
  spans?: number;
};

export type EventsGetParams = {
  /** EventId identifier */
  eventId: string;
  /** Span tree depth limit (number, "all" for unlimited, "no" to disable) */
  spans?: number;
};

export type TracesListParams = {
  /** Target identifier */
  target?: string;
  /** Number of traces (1-1000) */
  limit?: number;
  /** Search query (Sentry search syntax) */
  query?: string;
  /** Sort by: date, duration */
  sort?: string;
  /** Time period (e.g., "1h", "24h", "7d", "30d") */
  period?: string;
  /** Pagination cursor (use "last" to continue from previous page) */
  cursor?: string;
};

export type TracesGetParams = {
  /** TraceId identifier */
  traceId: string;
  /** Span tree depth limit (number, "all" for unlimited, "no" to disable) */
  spans?: number;
};

export type SpansListParams = {
  /** Target identifier */
  target?: string;
  /** Number of spans (<=1000) */
  limit?: number;
  /** Filter spans (e.g., "op:db", "duration:>100ms", "project:backend") */
  query?: string;
  /** Sort order: date, duration */
  sort?: string;
  /** Time period (e.g., "1h", "24h", "7d", "30d") */
  period?: string;
  /** Pagination cursor (use "last" to continue from previous page) */
  cursor?: string;
};

export type TeamsListParams = {
  /** Target identifier */
  target?: string;
  /** Maximum number of teams to list */
  limit?: number;
  /** Pagination cursor (use "last" to continue from previous page) */
  cursor?: string;
};

// --- SDK factory ---

/** Invoke function type from sdk-invoke.ts */
type Invoke = ReturnType<typeof buildInvoker>;

/**
 * Create the typed SDK method tree.
 * Called by createSentrySDK() with a bound invoker.
 * @internal
 */
export function createSDKMethods(invoke: Invoke) {
  return {
    organizations: {
    /** List organizations */
    list: (params?: OrganizationsListParams): Promise<SentryOrganization[]> =>
      invoke<SentryOrganization[]>(["org","list"], { limit: params?.limit }, []),
    /** View details of an organization */
    get: (params?: OrganizationsGetParams): Promise<SentryOrganization> =>
      invoke<SentryOrganization>(["org","view"], {}, params?.org ? [params.org] : []),
    },
    projects: {
    /** List projects */
    list: (params?: ProjectsListParams): Promise<{ data: SentryProject[]; hasMore: boolean; nextCursor?: string }> =>
      invoke<{ data: SentryProject[]; hasMore: boolean; nextCursor?: string }>(["project","list"], { limit: params?.limit, platform: params?.platform, cursor: params?.cursor }, params?.target ? [params.target] : []),
    /** View details of a project */
    get: (params?: ProjectsGetParams): Promise<SentryProject[]> =>
      invoke<SentryProject[]>(["project","view"], {}, params?.target ? [params.target] : []),
    },
    issues: {
    /** List issues in a project */
    list: (params: IssuesListParams): Promise<{ data: SentryIssue[]; hasMore: boolean; nextCursor?: string }> =>
      invoke<{ data: SentryIssue[]; hasMore: boolean; nextCursor?: string }>(["issue","list"], { query: params?.query, limit: params?.limit, sort: params?.sort, period: params?.period, cursor: params?.cursor }, [`${params.org}/${params.project}`]),
    /** View details of a specific issue */
    get: (params: IssuesGetParams): Promise<SentryIssue & { event: SentryEvent | null }> =>
      invoke<SentryIssue & { event: SentryEvent | null }>(["issue","view"], { spans: params?.spans }, [params.issueId]),
    },
    events: {
    /** View details of a specific event */
    get: (params: EventsGetParams): Promise<SentryEvent> =>
      invoke<SentryEvent>(["event","view"], { spans: params?.spans }, [params.eventId]),
    },
    traces: {
    /** List recent traces in a project */
    list: (params?: TracesListParams): Promise<{ data: TransactionListItem[]; hasMore: boolean; nextCursor?: string }> =>
      invoke<{ data: TransactionListItem[]; hasMore: boolean; nextCursor?: string }>(["trace","list"], { limit: params?.limit, query: params?.query, sort: params?.sort, period: params?.period, cursor: params?.cursor }, params?.target ? [params.target] : []),
    /** View details of a specific trace */
    get: (params: TracesGetParams): Promise<{ traceId: string; duration: number; spanCount: number; spans: TraceSpan[] }> =>
      invoke<{ traceId: string; duration: number; spanCount: number; spans: TraceSpan[] }>(["trace","view"], { spans: params?.spans }, [params.traceId]),
    },
    spans: {
    /** List spans in a project or trace */
    list: (params?: SpansListParams): Promise<{ data: SpanListItem[]; hasMore: boolean; nextCursor?: string }> =>
      invoke<{ data: SpanListItem[]; hasMore: boolean; nextCursor?: string }>(["span","list"], { limit: params?.limit, query: params?.query, sort: params?.sort, period: params?.period, cursor: params?.cursor }, params?.target ? [params.target] : []),
    },
    teams: {
    /** List teams */
    list: (params?: TeamsListParams): Promise<{ data: SentryTeam[]; hasMore: boolean; nextCursor?: string }> =>
      invoke<{ data: SentryTeam[]; hasMore: boolean; nextCursor?: string }>(["team","list"], { limit: params?.limit, cursor: params?.cursor }, params?.target ? [params.target] : []),
    },
  };
}

/** Return type of createSDKMethods — the typed SDK interface. */
export type SentrySDK = ReturnType<typeof createSDKMethods>;
