/**
 * Hand-written half of the published type declarations (`dist/index.d.cts` / `.d.mts`).
 *
 * The per-command `SentrySDK` types are generated by `generate-sdk.ts`; everything here
 * describes the library entry point itself.
 */

/** Location of the module `SentryOptions` is lifted from, relative to `packages/cli`. */
export const SDK_TYPES_PATH = "src/lib/sdk-types.ts";

const SENTRY_OPTIONS_START = "export type SentryOptions = {";
const SENTRY_OPTIONS_END = "\n};";

/**
 * Lifts the `SentryOptions` declaration verbatim out of `sdk-types.ts`.
 *
 * This used to be a hand-written copy, which drifted without anything failing: `headers` was
 * added to the source and worked at runtime in 0.44.0, yet consumers passing it got a type
 * error because the copy never learned about the option.
 */
export function extractSentryOptions(sdkTypesSource: string): string {
  const start = sdkTypesSource.indexOf(SENTRY_OPTIONS_START);
  const end =
    start === -1 ? -1 : sdkTypesSource.indexOf(SENTRY_OPTIONS_END, start);
  if (start === -1 || end === -1) {
    throw new Error(
      `Could not find the \`SentryOptions\` declaration in ${SDK_TYPES_PATH}.`
    );
  }
  return sdkTypesSource.slice(start, end + SENTRY_OPTIONS_END.length);
}

/** Assembles the entry-point declarations from the current `sdk-types.ts` source. */
export function buildCoreDeclarations(sdkTypesSource: string): string {
  return `${extractSentryOptions(sdkTypesSource)}

export type AsyncChannel<T> = AsyncIterable<T> & {
  push(value: T): void;
  close(): void;
  error(err: Error): void;
};

export declare class SentryError extends Error {
  readonly exitCode: number;
  readonly stderr: string;
  constructor(message: string, exitCode: number, stderr: string);
}

export declare function createSentrySDK(options?: SentryOptions): SentrySDK & {
  /** Run an arbitrary CLI command (escape hatch). Streaming flags return AsyncIterable. */
  run(...args: string[]): Promise<unknown> | AsyncIterable<unknown>;
};

export default createSentrySDK;
`;
}
